-- ==========================================
-- Natural Disaster Survival (NDS) Script
-- Gelişmiş Sürüm + Anti-Fling Korunması
-- ==========================================

-- Servisler
local Players = game:GetService("Players")
local Workspace = game:GetService("Workspace")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local player = Players.LocalPlayer

-- Ekran bildirimi (UI) için fonksiyon
local function sendNotification(title, text)
    game:GetService("StarterGui"):SetCore("SendNotification", {
            Title = title;
                    Text = text;
                            Duration = 5;
                                })
                                end

                                sendNotification("NDS Script", "Anti-Fling ve Tüm Özellikler Aktif!");

                                -- 1. Karakter Özelliklerini Güçlendirme (Hız ve Zıplama)
                                local function setupCharacter(char)
                                    local humanoid = char:WaitForChild("Humanoid")
                                        humanoid.WalkSpeed = 26 -- Hızlı kaçış için
                                            humanoid.JumpPower = 65
                                            end

                                            if player.Character then
                                                setupCharacter(player.Character)
                                                end
                                                player.CharacterAdded:Connect(setupCharacter)

                                                -- 2. Anti-Fling Koruma Sistemi (Savrulmayı ve Fırlatılmayı Engeller)
                                                RunService.Stepped:Connect(function()
                                                    local char = player.Character
                                                        if char and char:FindFirstChild("HumanoidRootPart") then
                                                                local rootPart = char.HumanoidRootPart
                                                                        
                                                                                -- Eğer karakter anormal bir hızla savrulmaya başlarsa hızı kes
                                                                                        if rootPart.AssemblyLinearVelocity.Magnitude > 150 then
                                                                                                    rootPart.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
                                                                                                                rootPart.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
                                                                                                                        end
                                                                                                                                
                                                                                                                                        -- Ekstra koruma: Karakterin yere sabit kalmasını destekle
                                                                                                                                                for _, part in pairs(char:GetChildren()) do
                                                                                                                                                            if part:IsA("BasePart") then
                                                                                                                                                                            part.CustomPhysicalProperties = PhysicalProperties.new(100, 0.3, 0.5, 1, 1)
                                                                                                                                                                                        end
                                                                                                                                                                                                end
                                                                                                                                                                                                    end
                                                                                                                                                                                                    end)

                                                                                                                                                                                                    -- 3. Tornado (Kasırga) Tespiti ve Koruma Sistemi
                                                                                                                                                                                                    Workspace.ChildAdded:Connect(function(child)
                                                                                                                                                                                                        if string.find(string.lower(child.Name), "tornado") then
                                                                                                                                                                                                                sendNotification("⚠️ DİKKAT!", "Tornado çıktı! Güvenliğe geçiliyor...");
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                local char = player.Character
                                                                                                                                                                                                                                        if char and char:FindFirstChild("HumanoidRootPart") then
                                                                                                                                                                                                                                                    -- Kulenin tepesine benzer güvenli bir koordinat
                                                                                                                                                                                                                                                                char.HumanoidRootPart.CFrame = CFrame.new(-25, 115, -100)
                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                            end)

                                                                                                                                                                                                                                                                            -- 4. Enkaz Çemberi (Debris Orbit) Sistemi
                                                                                                                                                                                                                                                                            local orbitRadius = 8 -- Çemberin yarıçapı
                                                                                                                                                                                                                                                                            local orbitSpeed = 3  -- Dönüş hızı
                                                                                                                                                                                                                                                                            local maxDebrisCount = 15 -- Maksimum parça sayısı
                                                                                                                                                                                                                                                                            local activeDebris = {}

                                                                                                                                                                                                                                                                            local function startDebrisOrbit()
                                                                                                                                                                                                                                                                                local count = 0
                                                                                                                                                                                                                                                                                    activeDebris = {}
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            for _, obj in pairs(Workspace:GetChildren()) do
                                                                                                                                                                                                                                                                                                    if obj:IsA("Part") and not obj.Anchored and obj.Size.Magnitude < 5 then
                                                                                                                                                                                                                                                                                                                if count < maxDebrisCount then
                                                                                                                                                                                                                                                                                                                                obj.CanCollide = false -- İçimizden geçsin, zarar vermesin
                                                                                                                                                                                                                                                                                                                                                table.insert(activeDebris, obj)
                                                                                                                                                                                                                                                                                                                                                                count = count + 1
                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                                            print(count .. " adet enkaz etrafına toplandı!")
                                                                                                                                                                                                                                                                                                                                                                                            end

                                                                                                                                                                                                                                                                                                                                                                                            -- Her karede parçaları döndürme döngüsü
                                                                                                                                                                                                                                                                                                                                                                                            RunService.RenderStepped:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                local char = player.Character
                                                                                                                                                                                                                                                                                                                                                                                                    if not char or not char:FindFirstChild("HumanoidRootPart") then return end
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            local rootPart = char.HumanoidRootPart
                                                                                                                                                                                                                                                                                                                                                                                                                local timeFactor = tick() * orbitSpeed
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                        for i, part in ipairs(activeDebris) do
                                                                                                                                                                                                                                                                                                                                                                                                                                if part and part.Parent then
                                                                                                                                                                                                                                                                                                                                                                                                                                            local angle = timeFactor + (i * (math.pi * 2 / #activeDebris))
                                                                                                                                                                                                                                                                                                                                                                                                                                                        local offsetX = math.cos(angle) * orbitRadius
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local offsetZ = math.sin(angle) * orbitRadius
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            part.CFrame = CFrame.new(rootPart.Position + Vector3.new(offsetX, 3, offsetZ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        part.CFrame = part.CFrame * CFrame.Angles(0, timeFactor, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            table.remove(activeDebris, i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- 5. Tuş Atamaları (Kısayollar)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UserInputService.InputBegan:Connect(function(input, gameProcessed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if gameProcessed then return end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- 'E' Tuşu: Acil yukarı çıkış
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if input.KeyCode == Enum.KeyCode.E then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local char = player.Character
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if char and char:FindFirstChild("HumanoidRootPart") then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    char.HumanoidRootPart.CFrame = char.HumanoidRootPart.CFrame + Vector3.new(0, 50, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Acil yükseklik kazanıldı!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- 'Q' Tuşu: Enkaz çemberini başlat/yenile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if input.KeyCode == Enum.KeyCode.Q then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startDebrisOrbit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    